---
# file: dependency.yml
- name: install packages
  sudo: yes
  apt:  "pkg={{ item }} update_cache=yes"
  with_items: ghc_dependencies
  when: package == "apt"

- name: install packages
  homebrew:  "pkg={{ item }} update_homebrew=yes"
  with_items: ghc_dependencies
  when: package == "homebrew"

